//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORUMLULUK_MERKEZLERI
    {
        public System.Guid som_Guid { get; set; }
        public short som_DBCno { get; set; }
        public Nullable<int> som_SpecRECno { get; set; }
        public Nullable<bool> som_iptal { get; set; }
        public Nullable<short> som_fileid { get; set; }
        public Nullable<bool> som_hidden { get; set; }
        public Nullable<bool> som_kilitli { get; set; }
        public Nullable<bool> som_degisti { get; set; }
        public Nullable<int> som_checksum { get; set; }
        public Nullable<short> som_create_user { get; set; }
        public System.DateTime som_create_date { get; set; }
        public Nullable<short> som_lastup_user { get; set; }
        public Nullable<System.DateTime> som_lastup_date { get; set; }
        public string som_special1 { get; set; }
        public string som_special2 { get; set; }
        public string som_special3 { get; set; }
        public string som_kod { get; set; }
        public string som_isim { get; set; }
        public Nullable<bool> som_DogrudanUrtSrmMrk { get; set; }
        public Nullable<byte> som_MasrafNereyeYuklenecek { get; set; }
        public string som_DagAnahKodu { get; set; }
        public string som_MuhArtikeli { get; set; }
        public Nullable<byte> som_MaliyetDagitimSekli { get; set; }
        public Nullable<byte> som_MaliyetDagitimKaynak { get; set; }
        public Nullable<byte> som_tipi { get; set; }
        public Nullable<int> som_satis_fiyat_liste_no { get; set; }
    }
}
